### ISSUE TITLE
How to activate file saving?

### ISSUE THREAD

**Issue by asitemade4u** [cshum/imagor#2]
Great tool!
The only question I have is how to activate file saving: I have defined the `FILE_STORAGE_BASE_DIR` in the `docker-compose.yml` file yet nothing happens when triggering the image treatments from the browser.

**Comment by cshum** [comment]
Can you share your `docker-compose.yml`?

**Comment by asitemade4u** [comment]
Here you go:
```yaml
version: "3"
services:
  imagor:
    image: shumc/imagor:latest
    container_name: igr
    restart: unless-stopped
    volumes:
      - /mnt/kuqfnl:/mnt/data
    environment:
      PORT: 8000
      IMAGOR_UNSAFE: 1
      FILE_LOADER_BASE_DIR: /mnt/data 
      FILE_STORAGE_BASE_DIR: /mnt/data 
    ports:
      - "7123:8000"
    labels:
        - 'com.centurylinklabs.watchtower.enable=true'
```
