### ISSUE TITLE
Is it possible to get original image from local storage?

### ISSUE THREAD

**Issue by glitterlip** [cshum/imagor#247]
Docker Compose example with file system, using mounted volume:

````
version: "3"
services:
  imagor:
    image: shumc/imagor:latest
    volumes:
      - ./:/mnt/data
    environment:
      PORT: 8000
      IMAGOR_UNSAFE: 1 # unsafe URL for testing

      FILE_LOADER_BASE_DIR: /mnt/data # enable file loader by specifying base dir

      FILE_STORAGE_BASE_DIR: /mnt/data # enable file storage by specifying base dir
      FILE_STORAGE_MKDIR_PERMISSION: 0755 # optional
      FILE_STORAGE_WRITE_PERMISSION: 0666 # optional

      FILE_RESULT_STORAGE_BASE_DIR: /mnt/data/result # enable file result storage by specifying base dir
      FILE_RESULT_STORAGE_MKDIR_PERMISSION: 0755 # optional
      FILE_RESULT_STORAGE_WRITE_PERMISSION: 0666 # optional
      
    ports:
      - "8000:8000"
````
If I try `http://localhost:8000/unsafe/filters:format(webp):quality(30)/imgs/1.jpg` would get  `no such host: https://imgs/1.jpg`

If I try `http://localhost:8003/unsafe/filters:format(webp):quality(30)/file://imgs/1.jpg` would get `Get \"file://imgs/1.jpg\": unsupported protocol scheme \"file\"`

How to tell imagor to load image to be processed from local storage eg: `/mnt/data/imgs/1.jpg` and save the processed image to `/mnt/data/imgs/1.webp `
