### ISSUE TITLE
Crash due to 'invalid memory address or nil pointer dereference' with GCloud result storage

### ISSUE THREAD

**Issue by sam-lewis-storyteq** [cshum/imagor#497]
Imagor has been working great for my but recently I am seeing occasional errors caused by `invalid memory address or nil pointer dereference` when using Imagor with GCloud result storage.

Sorry for the image, this seemed easier to read than the json logs:

![image](https://github.com/user-attachments/assets/42a8f13c-bef4-4433-94da-32f082deef82)

Setup:
- imagor:1.4.8
- GCloud result storage

I will test with the latest version of imagor but I cant see any changes to `blob.go` since 1.4.8.

Thanks for the amazing project!

**Comment by Infonautica** [comment]
Following the trace i suspect (but high chance i'm wrong) the issue could be somewhere there:
https://github.com/cshum/imagor/blob/master/blob.go#L285-L287

And as i understand both `b` and `reader` are present, so i don't really know. Hoping @cshum you have ideas

**Comment by sam-lewis-storyteq** [comment]
Possible duplicate of https://github.com/cshum/imagor/issues/401

**Comment by StepanKuksenko** [comment]
We experience the same issue. 
We had used Google Cloud Storage as image source with **S3Storage** loaded for long time and everything was fine (you can configure `AWS_` env variables to use GCS cloud because it is S3 compatible), but 2 days ago, we switched to **GCloudStorage** loader using the same GCS bucked and very soon I saw first `invalid memory address or nil pointer dereference` and since then we have it a few times a day.
So I believe the issue is somewhere in  **GCloudStorage** laoder.

**Comment by StepanKuksenko** [comment]
Switched back to S3CloudStorage loader using the same Google Cloud Storage, and the problem was solved.  

For those who wants to use GCS via AWS provider you can create S3 compatible service token for the bucket and set the fallowing envs for Imagor:
```yaml
  AWS_ACCESS_KEY_ID: <key-id>
  AWS_SECRET_ACCESS_KEY: <secret-key>
  AWS_REGION: <gcloud-region>
  S3_LOADER_BUCKET: <gcloud-bucket-name>
  S3_ENDPOINT: https://storage.googleapis.com

  # optional
  S3_FORCE_PATH_STYLE: '1'
  S3_LOADER_BASE_DIR: ""
```
