### ISSUE TITLE
Saved images are not treated

### ISSUE THREAD

**Issue by asitemade4u** [cshum/imagor#5]
- I am using version 0.2.4
- When saving images, they are identical to the original and do not bear the treatments applied on the fly.

**Comment by cshum** [comment]
The current storage stores the original image so it can be used by the loader in next run. Thats why the loader and storage is suggested to be configured on the same path.

I am interested in adding "result storage" support, just figuring what the storage path should look like

**Comment by asitemade4u** [comment]
OK, get it.
However think that saving the result would also be a great idea as it would allow for caching images generated in a certain set of circumstances that imagor used to generate them in the first place.
That's why you may want to include some sort of identifier into the image file name coming from the treatments that were applied to the original. Then, when applying the exact same treatments anew, being able to search for the image with same identifier in the cache instead of applying treatments again.

**Comment by cshum** [comment]
`shumc/imagor:0.5.5` now included result loader and storage.

#### Docker Compose Example

Imagor with File Loader and Storage using mounted volume:

```yaml
version: "3"
services:
  imagor:
    image: shumc/imagor:latest
    volumes:
      - ./:/mnt/data
    environment:
      PORT: 8000
      IMAGOR_UNSAFE: 1 # unsafe URL for testing
      
      FILE_LOADER_BASE_DIR: /mnt/data # enable file loader by specifying base dir
      FILE_STORAGE_BASE_DIR: /mnt/data # enable file storage by specifying base dir
      
      FILE_RESULT_LOADER_BASE_DIR: /mnt/data/result # enable file result loader by specifying base dir
      FILE_RESULT_STORAGE_BASE_DIR: /mnt/data/result # enable file result storage by specifying base dir
    ports:
      - "8000:8000"
```

Imagor with AWS S3 Loader and Storage:

```yaml
version: "3"
services:
  imagor:
    image: shumc/imagor:latest
    environment:
      PORT: 8000
      IMAGOR_SECRET: mysecret # secret key for URL signature
      AWS_ACCESS_KEY_ID: ...
      AWS_SECRET_ACCESS_KEY: ...
      AWS_REGION: ...
      
      S3_LOADER_BUCKET: mybucket # enable S3 loader by specifying loader bucket
      S3_LOADER_BASE_DIR: images # optional
      S3_STORAGE_BUCKET: mybucket # enable S3 storage by specifying storage bucket
      S3_STORAGE_BASE_DIR: images # optional
      
      S3_RESULT_LOADER_BUCKET: mybucket # enable S3 result loader by specifying loader bucket
      S3_RESULT_LOADER_BASE_DIR: images/result # optional
      S3_RESULT_STORAGE_BUCKET: mybucket # enable S3 result loader by specifying loader bucket
      S3_RESULT_STORAGE_BASE_DIR: images/result # optional
    ports:
      - "8000:8000"
```
